# Generated by Django 2.2.5 on 2020-11-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospital',
            new_name='Hospitais',
        ),
        migrations.RenameField(
            model_name='hospitais',
            old_name='conceito_hospital',
            new_name='conceito_hospitais',
        ),
        migrations.RenameField(
            model_name='hospitais',
            old_name='nome_hospital',
            new_name='nome_hospitais',
        ),
        migrations.RenameField(
            model_name='hospitais',
            old_name='tipo_hospital',
            new_name='tipo_hospitais',
        ),
    ]
